export const SET_SEARCHPAGE_POSTS = "SET_SEARCHPAGE_POSTS";
export const SET_SEARCHPAGE_QUERY = "SET_SEARCHPAGE_QUERY";
export const SET_SEARCHPAGE_FETCHING = "SET_SEARCHPAGE_FETCHING";
export const SET_SEARCHPAGE_ERROR = "SET_SEARCHPAGE_ERROR";
export const SET_SEARCHPAGE_HAS_MORE = "SET_SEARCHPAGE_HAS_MORE";
export const SET_SEARCHPAGE_PAGE_NUMBER = "SET_SEARCHPAGE_PAGE_NUMBER";
export const RESET_SEARCHPAGE_POSTS = "RESET_SEARCHPAGE_POSTS";