export const SET_HOMEPAGE_POSTS = "SET_HOMEPAGE_POSTS";
export const SET_HOMEPAGE_FETCHING = "SET_HOMEPAGE_FETCHING";
export const SET_HOMEPAGE_ERROR = "SET_HOMEPAGE_ERROR";
export const SET_HOMEPAGE_HAS_MORE = "SET_HOMEPAGE_HAS_MORE";
export const SET_HOMEPAGE_PAGE_NUMBER = "SET_HOMEPAGE_PAGE_NUMBER";
export const RESET_HOMEPAGE_POSTS = "RESET_HOMEPAGE_POSTS";