export const SET_POSTPAGE_POST = "SET_POSTPAGE_POST";
export const SET_POSTPAGE_AUTHOR = "SET_POSTPAGE_AUTHOR";
export const SET_POSTPAGE_LOADING = "SET_POSTPAGE_LOADING";
export const SET_POSTPAGE_ERROR = "SET_POSTPAGE_ERROR";
export const RESET_POSTPAGE_POST = "RESET_POSTPAGE_POST";